'''
MySQL-specific strings
-------------------------

Strings generated by this module are specific to MySQL.

Since this Library is MySQL-first, this module does as little as simply
sub-classing the default/common language class.
'''


from .Base import Base, language


@language
class MySQL(Base):
    pass
