'''
MySQL-specific strings
-------------------------

Strings generated by this module are specific to MySQL.

Since this Library is MySQL-first, this module does as little as simply
sub-classing the default/common language class.
'''


from .common import Base


class MySQL(Base):
  pass
